version: '3.8'

services:
  api:
    container_name: lateowl_api_container
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - ../.env           # main env
    environment:
      - PYTHON_EXECUTABLE=python
      - PYTHON_SCRIPT_PATH=./python/train_weights.py
    ports:
      - "3000:3000"
    networks:
      - lateowl_network
  postgres:
    container_name: lateowl_postgres_container
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - lateowl_postgres_data:${PGDATA}
      - ./postgres/postgres/install-uuid.sql:/docker-entrypoint-initdb.d/install-uuid.sql
    ports:
      - "5433:5432"
    networks:
      - lateowl_network
  pgadmin:
    container_name: lateowl_pgadmin_container
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - lateowl_pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - lateowl_network

  # --- STORAGE SECTION ---
  minio:
    container_name: minio_local
    image: quay.io/minio/minio:RELEASE.2025-04-03T14-56-28Z
    restart: unless-stopped
    command: server --console-address ":9001" /data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - lateowl_network

  # --- CACHE SECTION ---
  redis:
    container_name: lateowl_redis_container
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - lateowl_redis_data:/data
    networks:
      - lateowl_network

networks:
  lateowl_network:
    driver: bridge

volumes:
  lateowl_postgres_data:
  lateowl_pgadmin_data:
  minio_data:
  lateowl_redis_data:
